project:
  type: website
  output-dir: docs   # <--- AGREGA ESTA LÍNEA
resources:
  - CNAME

website:
#  twitter-card: false   # <--- Ponlo en false
#  open-graph: false     # <--- Ponlo en false
  title: "Rafael F. Navarro"
  description: "Rafael is a computational applied statistician working on Bayesian modeling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers
        text: Papers
      - href: teaching
        text: Teaching
      - href: media
        text: Media
      - href: talks
        text: Talks

  page-footer:
    left: "(c) Rafael F. Navarro, 2025–. [Disclaimer](disclaimer)"
  twitter-card: true
  open-graph: true
  google-analytics: "395640625"

format:
  html:
    theme:
      - cosmo
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    include-in-header:
      text: |
        <script type="application/ld+json">{"@context":"http://www.schema.org","@type":"Person","name":"Rafael Navarro Madrid","jobTitle":"Applied Statistician","description":"Applied Statistician specializing in Bayesian modeling across finance, marketing, and medicine. Dedicated to extracting high-value insights from data with the highest statistical rigor.","url":"https://rfnavarro.github.io","image":"","address":{"@type":"PostalAddress","addressLocality":"Lima","addressCountry":"Peru"},"worksFor":[{"@type":"Organization","name":"Cibertec"},{"@type":"Organization","name":"Mundo Pelotas"}],"alumniOf":[{"@type":"CollegeOrUniversity","name":"Universidad Nacional Agraria La Molina"},{"@type":"CollegeOrUniversity","name":"Universidad Peruana de Ciencias Aplicadas"}],"sameAs":["https://www.linkedin.com/in/rafael-navarro-madrid-24a467120/","https://www.instagram.com/fabiannavarromadrid/"],"birthDate":"1995-08-23","birthPlace":"Talara, Peru","nationality":{"@type":"Country","name":"Peru"}}</script>




